version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10-stretch
    steps:
    - checkout
    - restore_cache:
        keys:
        - node-modules-v1-{{ .Branch }}-{{ .Revision }}
        - node-modules-v1-{{ .Branch }}-
        - node-modules-v1-
    - run: yarn install
    - save_cache:
        key: node-modules-{{ .Branch }}-{{ .Revision }}
        paths:
        - "node_modules"
    - run: yarn run build
    - save_cache:
        key: build-{{ .Branch }}-{{ .Revision }}
        paths:
        - "build"
  deploy:
    machine:
      enabled: true
    steps:
    - restore_cache:
        keys:
        - build-{{ .Branch }}-{{ .Revision }}
        - build-{{ .Branch }}-
        - build-
    - add_ssh_keys
    - run:
        name: Deploy Over SSH
        command: |
          scp -r build/* $SSH_USER@$SSH_HOST:/var/www/html/

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master